config/routes.rb
Rails.application.routes.draw do


  resources :locations
  root :to => 'welcome#index'

  resources :user_sessions
  resources :users
  resources :locations
  resources :categories, only: [:show, :index]
  resources :restaurants do
    resources :reservations, only: [:index, :create]
  end


  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

  get "signup" => "users#new", :as => "sign_up"

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  # belongs_to :owner, class_name: "User"

  has_many :reservations
  belongs_to :category
  has_many :locations

  geocoded_by :location
  after_validation :geocode


  private

  def not_full?
    @reservation = reservations.where(start_time: start_time).sum(:party_size)
    :party_size <= capacity
  end


end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  def index

    @restaurants = if params[:search]
      Restaurant.where("LOWER(name) LIKE LOWER(?)", "%#{params[:search]}%")
      Restaurant.near(params[:search], 1, units: :km)
    elsif params[:longitude] && params[:latitude]
      Restaurant.near([params[:latitude], params[:longitude]], 1, units: :km)
    else
      Restaurant.all
    end

    respond_to do |format|
      format.html
      format.js
      format.json do
        # render json: @restaurants.map { |r|
        #   {
        #     id: r.id;
        #     name: r.name;
        #   }
        # }
      end
    end
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to @restaurant
    else
      render :new
    end
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @nearby_restaurants = @restaurant.nearbys(1, units: :km)

    if current_user
      @reservation = @restaurant.reservations.build
    end
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def update
    @restaurant = Restaurant.find(params[:id])

    if @restaurant.update_attributes(restaurant_params)
      redirect_to restaurant_path(@restaurant)
    else
      render :edit
    end
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy
    redirect_to restaurants_path
  end


  private
  def restaurant_params
    params.require(:restaurant).permit(:party_size, :category_id, :location, :capacity, :address)
  end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/restaurants/_form.html.erb
<%= form_for(@restaurant, :remote => true) do |f| %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :capacity %> <br/>
    <%= f.number_field :capacity %>
  </div>
  <div class="field">
    <%= f.label :location %> <br/>
    <%= f.text_field :location %>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/restaurants/_reservations.html.erb
<div id="reservation-list">

  <h1> <%= @restaurant.name %> Reservations </h1>
<!--  -->
</div>

app/views/restaurants/_restaurant.html.erb
<div class="restaurant">
  <h1> <%= restaurant.name  %></h1>
  <ul class="small-block-grid-2">
    <div class ="restinfo">
      <p class ="location">  <strong>Location:</strong>  <%= restaurant.location %></p>
      <p class ="capacity">  <strong>Capacity:</strong>  <%= restaurant.capacity %></p>
    </div>
    <div class="profpic">
      <p class ="profile_pic"> <img src="http://robohash.org/{{ address }}"></p>
    </div>
  </ul>
</div>

app/views/restaurants/create.html.erb
<h1>Restaurants#create</h1>
<p>Find me in app/views/restaurants/create.html.erb</p>

app/views/restaurants/edit.html.erb
<h1>Edit Restaurant</h1>

<%= render 'form' %>

app/views/restaurants/index.html.erb
<h1>Restaurants</h1>
<section>
  <button id="current-location">Find Restaurants Nearby</button>
</section>


<%= form_tag restaurants_path, method: :get, authentication: false, id: 'search-form' do %>
  <%= text_field_tag :search, params[:search] %>
  <%= submit_tag "Search" %>
<% end %>

<div id="restaurants">
  <%= render @restaurants %>
</div>

<%= link_to 'Create a Restaurant', new_restaurant_path %>


<script type="text/javascript">
  function display_search_results() {
    if (this.readyState === 4) {
      document.getElementById('restaurants').innerHTML = this.responseText;
    }
  }

  var form = document.getElementById('search-form');
  form.addEventListener('submit', function(event) {
    event.preventDefault();
    var searchValue = document.getElementById('search').value;

    var xhr = new XMLHttpRequest();
    xhr.onload = display_search_results;
    xhr.open('GET', '/restaurants?search=' + searchValue, true);
    xhr.setRequestHeader("X-Requested-With", "XMLHttpRequest");
    xhr.send();
  });
</script>

app/views/restaurants/index.js.erb
$('#restaurants').html("<%= escape_javascript(render @restaurants) %>");
$('#restaurants').html("<%= j(render @restaurants) %>");

app/views/restaurants/new.html.erb
<h1> New Restaurant </h1>
  <%= render 'form' %>

app/views/restaurants/show.html.erb
<p id="notice"><%= notice %></p>

<div id="restuarants">
  <%= render @restaurant%>

</div>

<!-- <section>
  <div id="map-canvas" data-longitude="<%= @restaurant.longitude.to_f %>" data-latitude="<%= @restaurant.latitude.to_f %>"></div>
</section>
 -->

<section>
<% if @nearby_restaurants.any? %>
<h3> Nearby Restaurants </h3>
  <ul>
    <% @nearby_restaurants.each do |r| %>
      <li> <%= r.name %> - <%= r.distance  %> </li>
    <% end %>
  </ul>
<% end %>
</section>


 <% if current_user %>
  <h4>New reservation</h4>
  <%= render :partial => 'reservations/form' %>

<% else %>
  <h4>Sign Up to make a reservation<h4>
  <%= link_to 'Sign Up', new_user_path %>
 <% end %>