config/routes.rb
Rails.application.routes.draw do


  resources :locations
  root :to => 'welcome#index'

  resources :user_sessions
  resources :users
  resources :locations
  resources :categories, only: [:show, :index]
  resources :restaurants do
    resources :reservations, only: [:index, :create]
  end


  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

  get "signup" => "users#new", :as => "sign_up"

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :restaurants
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @restaurants = Restaurant.all
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/index.html.erb
<h1>Categories</h1>

<% @categories.order("name asc").each do |category| %>
  <%= link_to category.name, "/categories/#{category.id}" %><br>
 <%= image src= "http://assets22.pokemon.com/assets/cms2/img/pokedex/full/#{pokemon.number.to_s.rjust(3, '0')}.png"} %>

<%end%>

app/views/categories/show.html.erb
<h1> <%= @category.name %></h1>

  <% @category.restaurants.order("created_at desc").each do |restaurant| %>
    <div>
      <%= link_to restaurant.name, restaurant_path(restaurant) %>
    </div>
  <%end%>

</div>


<!-- section>
  <div id="map-canvas"> data-longitude
  </div>

</section> -->